import { GameItem } from '../../models/ecosort.models';

/**
 * 100+ item bank for the Waste Sorting Game.
 * Each round randomly samples & shuffles a subset of these so repeat
 * plays feel fresh instead of the same fixed 8-item sequence.
 */
export const GAME_ITEM_BANK: GameItem[] = [
  // Wet Waste
  { id: 1,  name: 'Banana Peel',        correctCategory: 'Wet Waste', icon: '🍌' },
  { id: 2,  name: 'Apple Core',         correctCategory: 'Wet Waste', icon: '🍎' },
  { id: 3,  name: 'Orange Peel',        correctCategory: 'Wet Waste', icon: '🍊' },
  { id: 4,  name: 'Egg Shells',         correctCategory: 'Wet Waste', icon: '🥚' },
  { id: 5,  name: 'Leftover Rice',      correctCategory: 'Wet Waste', icon: '🍚' },
  { id: 6,  name: 'Tea Leaves',         correctCategory: 'Wet Waste', icon: '🍃' },
  { id: 7,  name: 'Coffee Grounds',     correctCategory: 'Wet Waste', icon: '☕' },
  { id: 8,  name: 'Potato Peel',        correctCategory: 'Wet Waste', icon: '🥔' },
  { id: 9,  name: 'Fish Bones',         correctCategory: 'Wet Waste', icon: '🐟' },
  { id: 10, name: 'Chicken Bones',      correctCategory: 'Wet Waste', icon: '🍗' },
  { id: 11, name: 'Vegetable Scraps',   correctCategory: 'Wet Waste', icon: '🥦' },
  { id: 12, name: 'Stale Bread',        correctCategory: 'Wet Waste', icon: '🍞' },
  { id: 13, name: 'Watermelon Rind',    correctCategory: 'Wet Waste', icon: '🍉' },
  { id: 14, name: 'Onion Skin',         correctCategory: 'Wet Waste', icon: '🧅' },
  { id: 15, name: 'Wilted Flowers',     correctCategory: 'Wet Waste', icon: '🥀' },
  { id: 16, name: 'Grass Clippings',    correctCategory: 'Wet Waste', icon: '🌿' },
  { id: 17, name: 'Dry Leaves',         correctCategory: 'Wet Waste', icon: '🍂' },
  { id: 18, name: 'Mango Seed',         correctCategory: 'Wet Waste', icon: '🥭' },
  { id: 19, name: 'Curd Leftovers',     correctCategory: 'Wet Waste', icon: '🥣' },
  { id: 20, name: 'Rotten Tomato',      correctCategory: 'Wet Waste', icon: '🍅' },
  { id: 21, name: 'Coconut Shell',      correctCategory: 'Wet Waste', icon: '🥥' },
  { id: 22, name: 'Corn Cob',           correctCategory: 'Wet Waste', icon: '🌽' },
  { id: 23, name: 'Pumpkin Scraps',     correctCategory: 'Wet Waste', icon: '🎃' },
  { id: 24, name: 'Used Tea Bag',       correctCategory: 'Wet Waste', icon: '🍵' },
  { id: 25, name: 'Leftover Curry',     correctCategory: 'Wet Waste', icon: '🍛' },

  // Recyclable Waste
  { id: 26, name: 'Soda Can',           correctCategory: 'Recyclable Waste', icon: '🥤' },
  { id: 27, name: 'Glass Jar',          correctCategory: 'Recyclable Waste', icon: '🫙' },
  { id: 28, name: 'Plastic Bottle',     correctCategory: 'Recyclable Waste', icon: '🧴' },
  { id: 29, name: 'Glass Bottle',       correctCategory: 'Recyclable Waste', icon: '🍾' },
  { id: 30, name: 'Tin Can',            correctCategory: 'Recyclable Waste', icon: '🥫' },
  { id: 31, name: 'Aluminium Foil',     correctCategory: 'Recyclable Waste', icon: '🧻' },
  { id: 32, name: 'Milk Carton',        correctCategory: 'Recyclable Waste', icon: '🥛' },
  { id: 33, name: 'Juice Carton',       correctCategory: 'Recyclable Waste', icon: '🧃' },
  { id: 34, name: 'Metal Spoon',        correctCategory: 'Recyclable Waste', icon: '🥄' },
  { id: 35, name: 'Steel Bowl',         correctCategory: 'Recyclable Waste', icon: '🍲' },
  { id: 36, name: 'Wine Bottle',        correctCategory: 'Recyclable Waste', icon: '🍷' },
  { id: 37, name: 'Ketchup Bottle',     correctCategory: 'Recyclable Waste', icon: '🍅' },
  { id: 38, name: 'Yogurt Cup',         correctCategory: 'Recyclable Waste', icon: '🥛' },
  { id: 39, name: 'Detergent Bottle',   correctCategory: 'Recyclable Waste', icon: '🧴' },
  { id: 40, name: 'Shampoo Bottle',     correctCategory: 'Recyclable Waste', icon: '🧴' },
  { id: 41, name: 'Mineral Water Bottle', correctCategory: 'Recyclable Waste', icon: '💧' },
  { id: 42, name: 'Beer Bottle',        correctCategory: 'Recyclable Waste', icon: '🍺' },
  { id: 43, name: 'Old Coins',          correctCategory: 'Recyclable Waste', icon: '🪙' },
  { id: 44, name: 'Aluminium Tray',     correctCategory: 'Recyclable Waste', icon: '🍱' },
  { id: 45, name: 'PET Container',      correctCategory: 'Recyclable Waste', icon: '🥡' },

  // Dry Waste
  { id: 46, name: 'Cardboard Box',      correctCategory: 'Dry Waste', icon: '📦' },
  { id: 47, name: 'Old Newspaper',      correctCategory: 'Dry Waste', icon: '📰' },
  { id: 48, name: 'Magazine',           correctCategory: 'Dry Waste', icon: '📖' },
  { id: 49, name: 'Plastic Bag',        correctCategory: 'Dry Waste', icon: '🛍️' },
  { id: 50, name: 'Bubble Wrap',        correctCategory: 'Dry Waste', icon: '📦' },
  { id: 51, name: 'Old Notebook',       correctCategory: 'Dry Waste', icon: '📓' },
  { id: 52, name: 'Wrapping Paper',     correctCategory: 'Dry Waste', icon: '🎁' },
  { id: 53, name: 'Broken Toy',         correctCategory: 'Dry Waste', icon: '🧸' },
  { id: 54, name: 'Old Cloth Rag',      correctCategory: 'Dry Waste', icon: '🧵' },
  { id: 55, name: 'Styrofoam Tray',     correctCategory: 'Dry Waste', icon: '🍱' },
  { id: 56, name: 'Chip Packet',        correctCategory: 'Dry Waste', icon: '🍟' },
  { id: 57, name: 'Tissue Paper',       correctCategory: 'Dry Waste', icon: '🧻' },
  { id: 58, name: 'Old Greeting Card',  correctCategory: 'Dry Waste', icon: '💌' },
  { id: 59, name: 'Broken Pencil',      correctCategory: 'Dry Waste', icon: '✏️' },
  { id: 60, name: 'Plastic Straw',      correctCategory: 'Dry Waste', icon: '🥤' },
  { id: 61, name: 'Old Shoe',           correctCategory: 'Dry Waste', icon: '👟' },
  { id: 62, name: 'Broken Umbrella',    correctCategory: 'Dry Waste', icon: '☂️' },
  { id: 63, name: 'Plastic Cutlery',    correctCategory: 'Dry Waste', icon: '🍴' },
  { id: 64, name: 'Cement Bag',         correctCategory: 'Dry Waste', icon: '🧱' },
  { id: 65, name: 'Old Calendar',       correctCategory: 'Dry Waste', icon: '📅' },
  { id: 66, name: 'Paper Cup',          correctCategory: 'Dry Waste', icon: '🥤' },
  { id: 67, name: 'Broken Plastic Toy', correctCategory: 'Dry Waste', icon: '🧸' },
  { id: 68, name: 'Old Curtains',       correctCategory: 'Dry Waste', icon: '🪟' },
  { id: 69, name: 'Packing Peanuts',    correctCategory: 'Dry Waste', icon: '📦' },
  { id: 70, name: 'Worn Out Sock',      correctCategory: 'Dry Waste', icon: '🧦' },

  // Hazardous Waste
  { id: 71, name: 'Lithium Battery',    correctCategory: 'Hazardous Waste', icon: '🔋' },
  { id: 72, name: 'Aerosol Spray',      correctCategory: 'Hazardous Waste', icon: '💨' },
  { id: 73, name: 'LED Bulb',           correctCategory: 'Hazardous Waste', icon: '💡' },
  { id: 74, name: 'Expired Medicine',   correctCategory: 'Hazardous Waste', icon: '💊' },
  { id: 75, name: 'Old Mobile Phone',   correctCategory: 'Hazardous Waste', icon: '📱' },
  { id: 76, name: 'Paint Can',          correctCategory: 'Hazardous Waste', icon: '🎨' },
  { id: 77, name: 'Motor Oil Can',      correctCategory: 'Hazardous Waste', icon: '🛢️' },
  { id: 78, name: 'Thermometer (Mercury)', correctCategory: 'Hazardous Waste', icon: '🌡️' },
  { id: 79, name: 'Old Charger Cable',  correctCategory: 'Hazardous Waste', icon: '🔌' },
  { id: 80, name: 'CFL Tube Light',     correctCategory: 'Hazardous Waste', icon: '💡' },
  { id: 81, name: 'Pesticide Bottle',   correctCategory: 'Hazardous Waste', icon: '☣️' },
  { id: 82, name: 'Nail Polish Bottle', correctCategory: 'Hazardous Waste', icon: '💅' },
  { id: 83, name: 'Old Laptop Battery', correctCategory: 'Hazardous Waste', icon: '🔋' },
  { id: 84, name: 'Syringe / Needle',   correctCategory: 'Hazardous Waste', icon: '💉' },
  { id: 85, name: 'Car Battery',        correctCategory: 'Hazardous Waste', icon: '🔋' },
  { id: 86, name: 'Used Cooking Gas Canister', correctCategory: 'Hazardous Waste', icon: '🛢️' },
  { id: 87, name: 'Insect Repellent Can', correctCategory: 'Hazardous Waste', icon: '🦟' },
  { id: 88, name: 'Hair Dye Bottle',    correctCategory: 'Hazardous Waste', icon: '🧪' },
  { id: 89, name: 'Old Smoke Detector', correctCategory: 'Hazardous Waste', icon: '🚨' },
  { id: 90, name: 'Broken CFL Bulb',    correctCategory: 'Hazardous Waste', icon: '💡' },

  // Mixed extras to push bank past 100
  { id: 91,  name: 'Cooking Oil Bottle',  correctCategory: 'Recyclable Waste', icon: '🛢️' },
  { id: 92,  name: 'Soup Tin',            correctCategory: 'Recyclable Waste', icon: '🥫' },
  { id: 93,  name: 'Cereal Box',          correctCategory: 'Dry Waste',        icon: '📦' },
  { id: 94,  name: 'Used Napkins',        correctCategory: 'Dry Waste',        icon: '🧻' },
  { id: 95,  name: 'Banana Stem',         correctCategory: 'Wet Waste',        icon: '🍌' },
  { id: 96,  name: 'Used Cotton Swabs',   correctCategory: 'Dry Waste',        icon: '🧴' },
  { id: 97,  name: 'Broken Glass Plate',  correctCategory: 'Recyclable Waste', icon: '🍽️' },
  { id: 98,  name: 'Old Keyboard',        correctCategory: 'Hazardous Waste',  icon: '⌨️' },
  { id: 99,  name: 'Spoiled Milk',        correctCategory: 'Wet Waste',        icon: '🥛' },
  { id: 100, name: 'Plastic Wrapper',     correctCategory: 'Dry Waste',        icon: '🍬' },
  { id: 101, name: 'Used Matchsticks',    correctCategory: 'Dry Waste',        icon: '🔥' },
  { id: 102, name: 'Coconut Husk',        correctCategory: 'Wet Waste',        icon: '🥥' },
  { id: 103, name: 'Old Router',          correctCategory: 'Hazardous Waste',  icon: '📡' },
  { id: 104, name: 'Broken Plate (Ceramic)', correctCategory: 'Dry Waste',     icon: '🍽️' },
  { id: 105, name: 'Used Diaper',         correctCategory: 'Dry Waste',        icon: '🧷' },
];
