// Generates src/environments/environment.ts and environment.prod.ts from
// environment variables at build time, so no real key/secret ever has to
// be committed to git. Run automatically before every `npm run build` /
// `npm start` via the "prebuild"/"prestart" npm script hooks.
//
// Local dev:  put your real values in a `.env` file (gitignored) in this
//             frontend/ folder, e.g.:
//               SUPABASE_URL=https://xxxx.supabase.co
//               SUPABASE_ANON_KEY=eyJ...
//               GEMINI_API_KEY=AIzaSy...
//               GEMINI_MODEL=gemini-2.5-flash
// Render:     set the same keys under Environment Variables in the
//             dashboard (or in render.yaml's envVars list) — no .env file
//             needed there, Render injects them directly into the build.

const fs = require('fs');
const path = require('path');

// Load a local .env file if present (zero extra dependency — tiny manual parser).
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim().replace(/^['"]|['"]$/g, '');
    if (!(key in process.env)) process.env[key] = value;
  }
}

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'GEMINI_API_KEY'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error(
    `\n❌ Missing required environment variable(s): ${missing.join(', ')}\n` +
    `   Create a frontend/.env file (see .env.example) for local dev,\n` +
    `   or set them in Render's dashboard under Environment Variables.\n`
  );
  process.exit(1);
}

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
const geminiApiKey = process.env.GEMINI_API_KEY;
const geminiModel = process.env.GEMINI_MODEL || 'gemini-2.5-flash';

function render(production) {
  return `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// Edit frontend/.env (local) or Render's Environment Variables instead,
// then re-run \`npm run build\` / \`npm start\`.
export const environment = {
  production: ${production},
  // ── Supabase ──────────────────────────────────────────────────────
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
  // ── Gemini AI ─────────────────────────────────────────────────────
  geminiApiKey: '${geminiApiKey}',
  geminiModel: '${geminiModel}'
};
`;
}

const outDir = path.join(__dirname, '..', 'src', 'environments');
fs.writeFileSync(path.join(outDir, 'environment.ts'), render(false));
fs.writeFileSync(path.join(outDir, 'environment.prod.ts'), render(true));

console.log('✅ Generated src/environments/environment.ts and environment.prod.ts from environment variables.');
